// <auto-generated />
namespace Rss.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class newsLink : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newsLink));
        
        string IMigrationMetadata.Id
        {
            get { return "201602241555280_newsLink"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
